<?php

namespace AppBundle\Repository;

/**
 * JobRecruiterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRecruiterRepository extends \Doctrine\ORM\EntityRepository
{
}
