<?php

namespace AppBundle\Repository;

/**
 * JobRecruiterFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRecruiterFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
