<?php

namespace AppBundle\Repository;

/**
 * JobSeeker_Applied_VacancyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeeker_Applied_VacancyRepository extends \Doctrine\ORM\EntityRepository
{
}
