<?php

namespace AppBundle\Repository;

/**
 * JobSeekerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerRepository extends \Doctrine\ORM\EntityRepository
{
}
