<?php

namespace AppBundle\Repository;

/**
 * JobSeekerAppliedVacancyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerAppliedVacancyRepository extends \Doctrine\ORM\EntityRepository
{
}
