<?php

namespace AppBundle\Repository;

/**
 * JobSeekerFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
