<?php

namespace AppBundle\Repository;

/**
 * OfficerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficerRepository extends \Doctrine\ORM\EntityRepository
{
}
