<?php

namespace AppBundle\Repository;

/**
 * SystemAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
