<?php

namespace AppBundle\Repository;

/**
 * TrainScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
