<?php

namespace AppBundle\Repository;

/**
 * VacancyFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacancyFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
