app:
    resource: "@AppBundle/Controller/"
    type:     annotation


# seeker_login_check:
#     	path: /login_check
#     	defaults:  { _controller: AppBundle:Security:login }

# recruiter_login_check:
#    		path: /login_check
#    		defaults:  { _controller: AppBundle:Security:login }